### ISSUE TITLE
Serial impl in Pi4J-1.1-SNAPSHOT

### ISSUE THREAD

**Issue by savageautomate** [slipperyseal/B9#1]
Just dropping a note as a "heads-up" to mention that when and if you upgrade to Pi4J 1.1 (currently only available as a SNAPSHOT build) that the Serial interfaces have changed a bit and the underlying implementation has been completely re-written to be more robust and provide more options.  

The source for the newer 1.1-SNAPSHOT builds is located in the `develop` branch of Pi4J.

Updated Serial Interfaces/Impl Code
https://github.com/Pi4J/pi4j/tree/develop/pi4j-core/src/main/java/com/pi4j/io/serial

Updated SerialExample.java
https://github.com/Pi4J/pi4j/blob/develop/pi4j-example/src/main/java/SerialExample.java

Thanks, Robert

**Comment by slipperyseal** [comment]
Thanks for the message Robert.

yes, i had noticed the new API was in development back on a previous
snapshot - i could see the String event being switched to a byte[]

i''ll create a branch on my project and track your API changes there.

**Comment by slipperyseal** [comment]
Pi4J Version 1.1 implemented (a while ago). closing issue.
